# Generated by Django 3.2 on 2021-06-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
