# Generated by Django 3.2 on 2021-06-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_customuser_privatekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='privateKey',
        ),
    ]
